koordinator-sh/website

docusaurus.config.js
Signed-off-by: hormes fanster.z@gmail.com
=> fix baseUrl of docusaurus

docs/installation.md
=> optimize installation page

docs/user-manuals/colocation-profile.md
Signed-off-by: Jason Liu <jasonliu747@gmail.com>
=> add colocation profile doc

README.md
=> add contributing section in README.md

src/pages/index.js, src/pages/index.module.css
=> add Getting Started Link in home page

blog/2022-03-31-release/index.md
=> fix release uri

blog/2022-03-31-release/index.md, docs/best-practices/colocation-of-spark-jobs.md, docs/installation.md
=> update installation doc

docs/best-practices/colocation-of-spark-jobs.md, docs/core-concepts/architecture.md, docs/core-concepts/priority.md, docs/core-concepts/qos.md, docs/user-manuals/colocation-profile.md
Signed-off-by: Li Yi <denverdino@gmail.com>
=> Typo fixing

blog/2022-04-19-release/index.md, docs/installation.md
=> add release-0.2.0 note and update installation doc

blog/2022-04-19-release/index.md
=> update release note v0.2.0

.gitignore, blog/2022-05-07-release/index.md, blog/authors.yml, docs/installation.md
Signed-off-by: Jason Liu <jasonliu747@gmail.com>
=> 📖 update release notes for v0.3.0

blog/2022-05-31-release/index.md, docs/installation.md
=> update release note and installation doc

docs/installation.md
=> update installation doc with v0.4.1

blog/2022-06-30-release/index.md
Signed-off-by: Jason Liu <jasonliu747@gmail.com>
=> v0.5 release blog of koordinator

docs/installation.md, versioned_docs/version-v0.5/installation.md
=> fix kubelet config for koord-runtime-proxy

blog/2022-05-07-release/index.md, blog/2022-05-31-release/index.md
update typo of config key with QOS to replace QoS and lsClass to replace ls
=> update typo of config key with QOS and lsClass

docs/installation.md
add more document for installation.
=> add more installation dependency description

blog/2022-08-04-release/index.md, docs/installation.md
Signed-off-by: Joseph <joseph.t.lee@outlook.com>
=> add v0.6.0 release note

versioned_docs/version-v0.6/designs/runtime-proxy.md
Signed-off-by: 佑祎 <zzw261520@alibaba-inc.com>
=> fix comma typo

docs/installation.md, versioned_docs/version-v0.6/installation.md
=> improve installation docs for koord-runtime-proxy

docs/designs/runtime-proxy.md, docs/installation.md, versioned_docs/version-v0.7/designs/runtime-proxy.md, versioned_docs/version-v0.7/installation.md
https://github.com/koordinator-sh/koordinator/issues/711
=> bugfix kubelet runtime parameters example

docs/installation.md
update kubelet  parameters under docker scenario
=> update kubelet  parameters under docker scenario

blog/2022-11-03-release/index.md, docs/installation.md
Signed-off-by: Joseph <joseph.t.lee@outlook.com>
=> add release v1.0 blog and update installation

README-zh.md, README.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/introduction.md
Translate i18n/zh-Hans/docusaurus-plugin-content-docs/current/introduction.md 
Translate i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation.md
=> Translate i18n/zh-Hans/docusaurus-plugin-content-docs/current/introduction.md i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation.md

i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/load-aware-scheduling.md
Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/load-aware-scheduling
=> Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/load-aware-scheduling

i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/gang-scheduling.md
Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/gang-scheduling
Signed-off-by: zhuhuijun <zhuhuijunzhj@gmail.com>
=> Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/gang-scheduling

i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/koordlet-overview.md
Translaten  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/koordlet-overview
=> Translaten  i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/koordlet-overview

i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/runtime-proxy.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/runtime-proxy.md
Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/runtime-proxy
=> Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/runtime-proxy

i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/overview.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/priority.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/qos.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/architecture/resource-model.md
Signed-off-by: LeoLiuYan <929908264@qq.com>
=> Feat to version 1.0

i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/koordlet-overview.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/load-aware-scheduling.md
=> zh koordlet load awre 1.0

i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/gang-scheduling.md
Signed-off-by: zhuhuijun <zhuhuijunzhj@gmail.com>
=> update gang-scheduling to version 1.0

i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/fine-grained-cpu-orchestration.md
Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/fine-grained-cpu-orchestration
=> Translaten i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/fine-grained-cpu-orchestration

i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/gang-scheduling.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/designs/gang-scheduling.md
Signed-off-by: zhuhuijun <zhuhuijunzhj@gmail.com>
=> translate gang-scheduling design

docs/user-manuals/colocation-profile.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/colocation-profile.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/load-aware-scheduling.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/colocation-profile.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.0/user-manuals/load-aware-scheduling.md
Signed-off-by: Joseph <joseph.t.lee@outlook.com>
=> update i18n version v1.0 with colocationProfile and load-aware-scheduling

docs/user-manuals/load-aware-descheduling.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/load-aware-descheduling.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.1/user-manuals/load-aware-descheduling.md, versioned_docs/version-v1.1/user-manuals/load-aware-descheduling.md
Signed-off-by: Joseph <joseph.t.lee@outlook.com>
=> update descheduling user manuals

docs/installation.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.1/installation.md, versioned_docs/version-v1.1/installation.md
Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>
Update version 1.1.1
=> Update version 1.1.1

blog/anolis-CPU-Co-location/index.md
This PR fixes a format error in blog 《龙蜥 plugsched 神器助力 Koordinator 云原生单机混部—— 内核 CPU QoS 揭秘》since the table is not showed correctly.
=> fix file format for plugsched blog

docs/architecture/priority.md
Fix the value range of priority class Mid.
=> arch: fix the priority range

docs/best-practices/anolis_plugsched.md, docs/user-manuals/cpu-qos.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/best-practices/anolis_plugsched.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/cpu-qos.md, sidebars.js
This PR add user manual `CPU QoS` and best practice for Anolis Plugsched plug-in to support CentOS 7.9 for cpu qos feature.
=> add user manual cpu qos and best practice plugsched

i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/resource-reservation.md
translate resource-reservation.md
=> translate resource-reservation.md

i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.2/best-practices/colocation-of-spark-jobs.md
chinese docs abourt best practice
=> docs: add chinese docs abourt best practice

docs/designs/nri-mode-resource-management.md
Fix CRIO version since CRIO support NRI from 1.26.0
=> fix crio version

docs/user-manuals/capacity-scheduling.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/multi-hierarchy-elastic-quota-management.md
Ref https://github.com/koordinator-sh/koordinator/issues/1473
=> Add doc for non-preemptible feature of Elastic Quota

docs/installation.md, docs/introduction.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation.md, i18n/zh-Hans/docusaurus-plugin-content-docs/version-v1.4/installation.md, versioned_docs/version-v1.4/installation.md, versioned_docs/version-v1.4/introduction.md
1. Fix a typo in Introduction.
2. Update the chart version in the Installation.
=> fix introduction typo, update installation for v1.4.1

i18n/zh-Hans/docusaurus-plugin-content-docs/current/designs/load-aware-scheduling.md
filter node which updateTime since now greater than nodeMetricExpirationSeconds.
=> fix doc:  filter node which updateTime since now greater than nodeMetricExpirationSeconds

docs/user-manuals/node-resource-fit-plus-scoring.md, i18n/zh-Hans/docusaurus-plugin-content-docs/current/user-manuals/node-resource-fit-plus-scoring.md
The ScarceResourceAvoidance plugin parameters in the document are missing apiversion and kind
=> fix: update NodeResourceFitPlus KEP
